const MARKETS = {
  Abia: [
    { name: "Aba International Market", img: "./markets/abia/aba-international.png", address:"Aba" },
    { name: "Alaoji Market", img: "./markets/abia/alaoji.jpg", address:"Alaoji" },
    { name: "Ariaria International Market", img: "./markets/abia/ariaria.jpeg", address:"Aba" },
    { name: "Eziukwu Market", img: "./markets/abia/eziukwu.jpeg", address:"Eziukwu" },
    { name: "Ikwuano Market", img: "./markets/abia/ikwuano.jpg", address:"Ikwuano" },
    { name: "Ndiegoro Market", img: "./markets/abia/ndiegoro.jpg", address:"Ndiegoro" },
    { name: "Ohia Market", img: "./markets/abia/ohia.jpg", address:"Ohia" },
    { name: "Oke Ikpe Market", img: "./markets/abia/okeikpe.jpg", address:"Okeikpe" },
    { name: "Oriendu Market", img: "./markets/abia/oriendu.jpeg", address:"Oriendu" },
    { name: "Ubakala Market", img: "./markets/abia/ubakala.jpg", address:"Ubakala" },
    { name: "Umuahia Main Market", img: "./markets/abia/umuahia.jpg", address:"Umuahia" },
    { name: "Umuocham Market", img: "./markets/abia/umuocham.jpeg", address:"Umuocham" },
    { name: "Uzuakoli Market", img: "./markets/abia/uzuakoli.jpeg", address:"Uzuakoli" },
  ],

  "Akwa-Ibom": [
    { name: "Akamkpa Timber Market", img: "./markets/akwa-ibom/akamkpa.jpg", address:"Akamkpa" },
    { name: "Akpabuyo Main Market", img: "./markets/akwa-ibom/akpabuyo.jpg", address:"Akpabuyo" },
    { name: "Boki Market", img: "./markets/akwa-ibom/boki.jpg", address:"Boki" },
    { name: "Eket Fish Market", img: "./markets/akwa-ibom/eket-fish.jpg", address:"Eket, Akwa Ibom" },
    { name: "Eket Main Market", img: "./markets/akwa-ibom/eket-main.jpg", address:"Eket, Akwa Ibom" },
    { name: "Esuk Mba Market", img: "./markets/akwa-ibom/esuk-mba.jpg", address:"Akpabuyo" },
    { name: "Etinan Main Market", img: "./markets/akwa-ibom/etinan.jpeg", address:"Etinan, Akwa Ibom" },
    { name: "Ikono Main Market", img: "./markets/akwa-ibom/ikono.jpeg", address:"Ikono, Akwa Ibom" },
    { name: "Ikot Abasi Main Market", img: "./markets/akwa-ibom/ikot-abasi.jpg", address:"Ikot Abasi, Akwa Ibom" },
    { name: "Ikot Akpan Market", img: "./markets/akwa-ibom/ikot-akpan.jpg", address:"Ikot Akpan, Akwa Ibom" },
    { name: "Itam Market", img: "./markets/akwa-ibom/itam.jpeg", address:"Itam, Akwa Ibom" },
    { name: "Nto Edino Market", img: "./markets/akwa-ibom/ntoedino.jpeg", address:"Nto Edino, Akwa Ibom" },
    { name: "Oron Fish Market", img: "./markets/akwa-ibom/oron-fish.jpeg", address:"Oron, Akwa Ibom" },
    { name: "Urua Akpan Ete Market", img: "./markets/akwa-ibom/urua-akpan-ete.jpeg", address:"Urua Akpan Ete, Akwa Ibom" },
    { name: "Urua Ikono Market", img: "./markets/akwa-ibom/urua-ikono.jpeg", address:"Urua Ikono, Akwa Ibom" },
  ],
  
  Adamawa: [
    { name: "Demsa Market", img: "./markets/adamawa/demsa.jpg", address: "Demsa Town, Demsa LGA" },
    { name: "Ganye Market", img: "./markets/adamawa/ganye.jpg", address: "Ganye Town, Ganye LGA" },
    { name: "Gombi Market", img: "./markets/adamawa/gombi.jpg", address: "Gombi Town, Gombi LGA" },    
    { name: "Gurin Market", img: "./markets/adamawa/gurin.jpg", address: "Gurin Town, Gurin LGA" },
    { name: "Hong Market", img: "./markets/adamawa/hong.jpg", address: "Hong Town, Hong LGA" },
    { name: "Jimeta Main Market", img: "./markets/adamawa/jimeta.jpg", address: "Jimeta, Yola North LGA" },
    { name: "Lamurde Market", img: "./markets/adamawa/lamurde.jpg", address: "Lamurde Town, Lamurde LGA" },
    { name: "Maiha Market", img: "./markets/adamawa/maiha.jpg", address: "Maiha Town, Maiha LGA" },
    { name: "Michika Market", img: "./markets/adamawa/michika.jpg", address: "Michika Town, Michika LGA" },
    { name: "Mubi Main Market", img: "./markets/adamawa/mubi.jpg", address: "Mubi Town, Mubi North LGA" },
    { name: "Numan Market", img: "./markets/adamawa/numan.jpg", address: "Numan Town, Numan LGA" },
    { name: "Shelleng Market", img: "./markets/adamawa/shelleng.jpg", address: "Shelleng Town, Shelleng LGA" },
    { name: "Song Market", img: "./markets/adamawa/song.jpg", address: "Song Town, Song LGA" },
  ],

  Anambra: [
    { name: "Afor Igwe Market", img: "./markets/anambra/afor-igwe.jpg", address:"Afor Igwe", city:"Anambra", description:"Lorem Ipsum" },
    { name: "Amaenyi Market", img: "./markets/anambra/amaenyi.jpeg", address:"Amaenyi, Anambra" },
    { name: "Bridgehead Market", img: "./markets/anambra/bridgehead.jpg", address:"Bridgehead, Anambra" },
    { name: "Eke Amaobi Market", img: "./markets/anambra/ekeamaobi.jpg", address:"Eke Amaobi, Anambra" },
    { name: "Eke Awka Market", img: "./markets/anambra/ekeawka.jpeg", address:"Eke Awka, Anambra" },
    { name: "Eke Ekwulobia Market", img: "./markets/anambra/ekeekwulobia.jpeg", address:"Eke Ekwulobia, Anambra" },
    { name: "Eke Market", img: "./markets/anambra/eke.jpeg", address:"Eke Aguleri, Anambra" },
    { name: "Nkwo Ekwulobia Market", img: "./markets/anambra/nkwo-ekwulobia.jpg", address:"Nkwo Ekwulobia, Anambra" },
    { name: "Nkwo Nnewi Market", img: "./markets/anambra/nkwo-nnewi.jpeg", address:"Nkwo Nnewi, Anambra" },
    { name: "Nkwelle Market", img: "./markets/anambra/nkwelle.jpg", address:"Nkwelle, Anambra" },
    { name: "Nnewi Spare Parts Market", img: "./markets/anambra/nnewi-spareparts.png", address:"Nnewi, Anambra" },
    { name: "Ochanja Market", img: "./markets/anambra/ochanja.jpg", address:"Ochanja, Anambra" },
    { name: "Onitsha Main Market", img: "./markets/anambra/onitsha.jpg", address:"Onitsha, Anambra" },
    { name: "Relief Market", img: "./markets/anambra/relief.jpg", address:"Relief, Anambra" },
    { name: "Uru Market", img: "./markets/anambra/uru.jpg", address:"Uru, Anambra" },
  ],

  Bauchi: [
    { name: "Bakaro Market", img: "./markets/bauchi/bakaro.jpg", address: "Bauchi, Bauchi State" },
    { name: "C & C Market", img: "./markets/bauchi/c&c.jpg", address: "Bauchi, Bauchi State" },
    { name: "Central Market", img: "./markets/bauchi/central.jpg", address: "Bauchi, Bauchi State" },
    { name: "Digare Market", img: "./markets/bauchi/digare.jpg", address: "Bauchi, Bauchi State" },
    { name: "Durum Village Market", img: "./markets/bauchi/durum.jpg", address: "Bauchi, Bauchi State" },
    { name: "Gaji Market", img: "./markets/bauchi/gaji.jpg", address: "Bauchi, Bauchi State" },
    { name: "Gwallameji Market", img: "./markets/bauchi/gwallameji.jpg", address: "Bauchi, Bauchi State" },
    { name: "Muda Lawal Market", img: "./markets/bauchi/muda-lawal.jpg", address: "Bauchi, Bauchi State" },
    { name: "Nabardo Market", img: "./markets/bauchi/nabardo.jpg", address: "Bauchi, Bauchi State" },
    { name: "Sabon Kasuwa Market", img: "./markets/bauchi/sabon-kasuwa.jpg", address: "Bauchi, Bauchi State" },
    { name: "Sade Market", img: "./markets/bauchi/sade.jpg", address: "Darazo LGA, Bauchi State" },
    { name: "Soro Cattle Market", img: "./markets/bauchi/soro.jpg", address: "Toro, Bauchi State" },
    { name: "Village Square Market", img: "./markets/bauchi/village-square.jpeg", address: "Azare, Bauchi State" },
    { name: "Wunti Market", img: "./markets/bauchi/wunti.jpg", address: "Bauchi, Bauchi State" },
  ],

  Bayelsa: [
    { name: "Agudama Market", img: "./markets/bayelsa/agudama.jpg", address: "Agudama Town" },
    { name: "Amassoma Market", img: "./markets/bayelsa/amassoma.jpg", address: "Amassoma Town" },
    { name: "Brass Market", img: "./markets/bayelsa/brass.jpeg", address: "Brass Town" },
    { name: "Ekeremor Market", img: "./markets/bayelsa/ekeremor.jpg", address: "Ekeremor Town" },
    { name: "Kaiama Market", img: "./markets/bayelsa/kaiama.jpg", address: "Kaiama Town" },
    { name: "Nembe Market", img: "./markets/bayelsa/nembe.jpg", address: "Nembe Town" },
    { name: "Odi Market", img: "./markets/bayelsa/odi.jpg", address: "Odi Town" },
    { name: "Ogbia Market", img: "./markets/bayelsa/ogbia.jpg", address: "Ogbia Town" },
    { name: "Okolobiri Market", img: "./markets/bayelsa/okolobiri.jpg", address: "Okolobiri Town" },
    { name: "Oporoma Market", img: "./markets/bayelsa/oporoma.jpg", address: "Oporoma Town" },
    { name: "Otueke Market", img: "./markets/bayelsa/otueke.jpg", address: "Otueke Town" },
    { name: "Sagbama Market", img: "./markets/bayelsa/sagbama.jpg", address: "Sagbama Town" },
    { name: "Swali Market", img: "./markets/bayelsa/swali.jpg", address: "Yenagoa" },
    { name: "Tombia Market", img: "./markets/bayelsa/tombia.jpg", address: "Tombia Town" },
    { name: "Yenagoa Main Market", img: "./markets/bayelsa/yenagoa.jpg", address: "Yenagoa" },
  ],

  Benue: [
    { name: "Achia Market", img: "./markets/benue/achia.jpeg", address: "Kwande LGA, Benue State" },
    { name: "Ada Market", img: "./markets/benue/ada.jpeg", address: "Kwande LGA, Benue State" },
    { name: "Adikpo Market", img: "./markets/benue/adikpo.jpg", address: "Adikpo, Kwande LGA, Benue State" },
    { name: "Adu Market", img: "./markets/benue/adu.jpeg", address: "Kwande LGA, Benue State" },
    { name: "Akpehe Market", img: "./markets/benue/akpehe.jpeg", address: "Makurdi, Benue State" },
    { name: "Gboko Main Market", img: "./markets/benue/gboko.jpeg", address: "Gboko, Benue State" },
    { name: "High-Level Market", img: "./markets/benue/high-level.jpg", address: "Makurdi, Benue State" },
    { name: "Iyon Market", img: "./markets/benue/iyon.jpeg", address: "Kwande LGA, Benue State" },
    { name: "Kookoko Market", img: "./markets/benue/kookoko.jpeg", address: "Kwande LGA, Benue State" },
    { name: "North Bank Market", img: "./markets/benue/north-bank.jpeg", address: "Makurdi, Benue State" },
    { name: "Otukpo Main Market", img: "./markets/benue/otukpo-main.jpg", address: "Otukpo, Benue State" },
    { name: "Railway Market", img: "./markets/benue/railway.jpeg", address: "Makurdi, Benue State" },
    { name: "Wadata Market", img: "./markets/benue/wadata.jpeg", address: "Makurdi, Benue State" },
    { name: "Wurukum Market", img: "./markets/benue/wurukum.jpg", address: "Makurdi, Benue State" },
  ],

  Borno: [
    { name: "Monday Market", img: "./markets/borno/monday.jpg", address: "Maiduguri City, Maiduguri LGA" },
    { name: "Baga Fish Market", img: "./markets/borno/baga.jpg", address: "Baga Town, Kukawa LGA" },
    { name: "Gamboru Market", img: "./markets/borno/gamboru.jpg", address: "Gamboru Ngala, Ngala LGA" },
    { name: "Biu Market", img: "./markets/borno/biu.jpg", address: "Biu Town, Biu LGA" },
    { name: "Monguno Market", img: "./markets/borno/monguno.jpg", address: "Monguno Town, Monguno LGA" },
    { name: "Dikwa Market", img: "./markets/borno/dikwa.jpg", address: "Dikwa Town, Dikwa LGA" },
    { name: "Gwoza Market", img: "./markets/borno/gwoza.jpg", address: "Gwoza Town, Gwoza LGA" },
    { name: "Chibok Market", img: "./markets/borno/chibok.jpeg", address: "Chibok Town, Chibok LGA" },
    { name: "Askira/Uba Market", img: "./markets/borno/uba.jpg", address: "Askira Town, Askira/Uba LGA" },
    { name: "Konduga Market", img: "./markets/borno/konduga.jpg", address: "Konduga Town, Konduga LGA" },
    { name: "Mafa Market", img: "./markets/borno/mafa.jpg", address: "Mafa Town, Mafa LGA" },
    { name: "Nganzai Market", img: "./markets/borno/nganzai.jpg", address: "Nganzai Town, Nganzai LGA" },
  ],

  "Cross-River": [
    { name: "Akamkpa Timber Market", img: "./markets/cross-river/akamkpa.jpg", address: "Akamkpa" },
    { name: "Akpabuyo Main Market", img: "./markets/cross-river/akpabuyo.jpg", address: "Akpabuyo" },
    { name: "Boki Market", img: "./markets/cross-river/boki.jpg", address: "Boki" },
    { name: "Esuk Mba Market", img: "./markets/cross-river/esuk-mba.jpg", address: "Akpabuyo" },
    { name: "Marian Market", img: "./markets/cross-river/marian.jpg", address: "Calabar" },
    { name: "Mbube Market", img: "./markets/cross-river/mbube.jpg", address: "Ogoja" },
    { name: "Ogoja Market", img: "./markets/cross-river/ogoja.jpg", address: "Ogoja" },
    { name: "Okuku Market", img: "./markets/cross-river/okuku.jpg", address: "Yala" },
    { name: "Watt Market", img: "./markets/cross-river/watt.jpg", address: "Calabar" },
  ],

  Delta: [
    { name: "Abraka Market", img: "./markets/delta/abraka.jpg", address: "Asaba" },
    { name: "Bomadi Market", img: "./markets/delta/bomadi.jpg", address: "Bomadi" },
    { name: "Burutu Market", img: "./markets/delta/burutu.jpg", address: "Burutu" },
    { name: "Igbudu Market", img: "./markets/delta/igbudu.jpg", address: "Warri" },
    { name: "Issele-Uku Market", img: "./markets/delta/issele-uku.jpeg", address: "Issele-Uku" },
    { name: "Koko Market", img: "./markets/delta/koko.jpg", address: "Koko" },
    { name: "Kwale Market", img: "./markets/delta/kwale.jpg", address: "Kwale" },
    { name: "Ogbe-Ijoh Market", img: "./markets/delta/ogbe-ijoh.jpg", address: "Warri" },
    { name: "Ogbogonogo Market", img: "./markets/delta/ogbogonogo.jpg", address: "Asaba" },
    { name: "Ogwashi-Uku Market", img: "./markets/delta/ogwashi-uku.jpg", address: "Ogwashi-Uku" },
    { name: "Oleh Market", img: "./markets/delta/oleh.jpg", address: "Oleh" },
    { name: "Ozoro Market", img: "./markets/delta/ozoro.jpg", address: "Ozoro" },
    { name: "Patani Market", img: "./markets/delta/patani.jpg", address: "Patani" },
    { name: "Sapele Main Market", img: "./markets/delta/sapele-main.jpg", address: "Sapele" },
    { name: "Ughelli Main Market", img: "./markets/delta/ughelli.jpg", address: "Ughelli" },
  ],

  Ebonyi: [
    { name: "Abakaliki International Market", img: "./markets/ebonyi/abakaliki.jpg", address: "Abakaliki" },
    { name: "Aho Market", img: "./markets/ebonyi/aho.jpg", address: "Ezza" },
    { name: "Ahia Ofu Market", img: "./markets/ebonyi/ahia-ofu.jpg", address: "Abakaliki" },
    { name: "Eke Imoha Market", img: "./markets/ebonyi/eke-imoha.jpg", address: "Ezza" },
    { name: "Eke Afikpo Market", img: "./markets/ebonyi/eke-afikpo.jpg", address: "Afikpo" },
    { name: "Eke Ishiagu Market", img: "./markets/ebonyi/eke-ishiagu.jpg", address: "Ishiagu" },
    { name: "Eke Okposi Market", img: "./markets/ebonyi/eke-okposi.jpg", address: "Okposi" },
    { name: "Mgbukobe Market", img: "./markets/ebonyi/mgbukobe.jpg", address: "Abakaliki" },
    { name: "Nkwo Market", img: "./markets/ebonyi/nkwo.jpg", address: "Ezza" },
    { name: "Onueke Market", img: "./markets/ebonyi/onueke.jpg", address: "Onueke" },
    { name: "Orie Egbe Market", img: "./markets/ebonyi/orie-egbe.jpg", address: "Amudo" },
    { name: "Orie Market", img: "./markets/ebonyi/orie.jpg", address: "Ezza" },
    { name: "St. Margaret Umahi International Market", img: "./markets/ebonyi/st-margaret.jpg", address: "Abakaliki" },
    { name: "Ugwuachara Market", img: "./markets/ebonyi/ugwuachara.jpg", address: "Abakaliki" },
    { name: "Ukwuagba Market", img: "./markets/ebonyi/ukwuagba.jpg", address: "Ngbo" },
  ],

  Edo: [
    { name: "Auchi Main Market", img: "./markets/edo/auchi.jpg", address: "Auchi" },
    { name: "Ekiosa Market", img: "./markets/edo/ekiosa.jpg", address: "Benin City" },
    { name: "Ekiuwa Market", img: "./markets/edo/ekiuwa.jpg", address: "Benin City" },
    { name: "Ekpoma Market", img: "./markets/edo/ekpoma.jpg", address: "Ekpoma" },
    { name: "Igarra Market", img: "./markets/edo/igarra.jpg", address: "Igarra" },
    { name: "Igueben Market", img: "./markets/edo/igueben.jpg", address: "Igueben" },
    { name: "Ikpoba Hill Market", img: "./markets/edo/ikpoba.jpg", address: "Benin City" },
    { name: "New Benin Market", img: "./markets/edo/new-benin.jpg", address: "Benin City" },
    { name: "Oba Market", img: "./markets/edo/oba.jpg", address: "Benin City" },
    { name: "Okada Market", img: "./markets/edo/okada.png", address: "Okada" },
    { name: "Oliha Market", img: "./markets/edo/oliha.jpeg", address: "Benin City" },
    { name: "Oregbeni Market", img: "./markets/edo/oregbeni.jpg", address: "Benin City" },
    { name: "Ubiaja Market", img: "./markets/edo/ubiaja.jpg", address: "Ubiaja" },
    { name: "Uromi Market", img: "./markets/edo/uromi.jpeg", address: "Uromi" },
    { name: "Uselu Market", img: "./markets/edo/uselu.jpg", address: "Benin City" },
  ],

  Ekiti: [
    { name: "Aramoko Market", img: "./markets/ekiti/aramoko.jpg", address:"Aramoko-Ekiti" },
    { name: "Bisi Market", img: "./markets/ekiti/bisi.jpg", address:"Ado-Ekiti" },
    { name: "Erekesan Market", img: "./markets/ekiti/erekesan.jpg", address:"Ado-Ekiti" },
    { name: "Ifaki Market", img: "./markets/ekiti/ifaki.jpeg", address:"Ifaki-Ekiti" },
    { name: "Igede Market", img: "./markets/ekiti/igede.jpg", address:"Igede-Ekiti" },
    { name: "Ikere Ekiti Market", img: "./markets/ekiti/ikere.jpeg", address:"Ikere-Ekiti" },
    { name: "Iye Ekiti Market", img: "./markets/ekiti/iye.jpeg", address:"Iye-Ekiti" },
    { name: "Oja Oba Market", img: "./markets/ekiti/oja-oba.jpg", address:"Ado-Ekiti" },
    { name: "Oja Odo Oro Market", img: "./markets/ekiti/odo-oro.jpg", address:"Odo Oro-Ekiti" },
    { name: "Otun Ekiti Market", img: "./markets/ekiti/otun.jpeg", address:"Otun-Ekiti" },
  ],

  Enugu: [
    { name: "9th Mile Corner Market", img: "./markets/enugu/9th-mile.jpg", address: "Udi" },
    { name: "Abakpa Market", img: "./markets/enugu/abakpa.jpg", address: "Abakpa, Enugu" },
    { name: "Akwata Market", img: "./markets/enugu/akwata.jpg", address: "Enugu" },
    { name: "Artisan Market", img: "./markets/enugu/artisan.jpg", address: "Enugu" },
    { name: "Coal Camp Market", img: "./markets/enugu/coal-camp.jpg", address: "Enugu" },
    { name: "Eke Agbani Market", img: "./markets/enugu/eke-agbani.jpg", address: "Agbani" },
    { name: "Emene Market", img: "./markets/enugu/emene.jpg", address: "Emene" },
    { name: "Garki Market", img: "./markets/enugu/garki.jpg", address: "Enugu" },
    { name: "Kenyatta Market", img: "./markets/enugu/kenyatta.jpg", address: "Uwani, Enugu" },
    { name: "Mayor Market", img: "./markets/enugu/mayor.jpg", address: "Enugu" },
    { name: "New Market", img: "./markets/enugu/new.jpg", address: "Enugu" },
    { name: "Nsukka Market", img: "./markets/enugu/nsukka.jpg", address: "Nsukka" },
    { name: "Ogbete Main Market", img: "./markets/enugu/ogbete.jpg", address: "Enugu" },
    { name: "Orie Orba Market", img: "./markets/enugu/orie-orba.jpg", address: "Orba" },
  ],

  FCT: [
    { name: "Apo Mechanic Village Market", img: "./markets/abuja/apo.jpg", address: "Apo, Abuja" },
    { name: "Dei-Dei Building Materials Market", img: "./markets/abuja/dei-dei.jpg", address: "Dei-Dei, Abuja" },
    { name: "Dutse Market", img: "./markets/abuja/dutse.jpg", address: "Dutse Alhaji, Abuja" },
    { name: "Garki International Market", img: "./markets/abuja/garki.jpg", address: "Garki, Abuja" },
    { name: "Gudu Market", img: "./markets/abuja/gudu.jpg", address: "Gudu, Abuja" },
    { name: "Gwagwalada Market", img: "./markets/abuja/gwagwalada.jpg", address: "Gwagwalada, Abuja" },
    { name: "Jabi Motor Park Market", img: "./markets/abuja/jabi.jpg", address: "Jabi, Abuja" },
    { name: "Kado Fish Market", img: "./markets/abuja/kado.jpg", address: "Kado, Abuja" },
    { name: "Karu Market", img: "./markets/abuja/karu.jpg", address: "Karu, Abuja" },
    { name: "Kubwa Market", img: "./markets/abuja/kubwa.jpg", address: "Kubwa, Abuja" },
    { name: "Lugbe Market", img: "./markets/abuja/lugbe.jpg", address: "Lugbe, Abuja" },
    { name: "Nyanya Market", img: "./markets/abuja/nyanya.jpg", address: "Nyanya, Abuja" },
    { name: "Utako Market", img: "./markets/abuja/utako.jpg", address: "Utako, Abuja" },
    { name: "Wuse Market", img: "./markets/abuja/wuse.jpg", address: "Wuse, Abuja" },
    { name: "Zuba Fruit Market", img: "./markets/abuja/zuba.jpg", address: "Zuba, Abuja" },
  ],

  Gombe: [
    { name: "Bajoga Market", img: "./markets/gombe/bajoga.jpg", address: "Bajoga Town, Funakaye LGA" },
    { name: "Billiri Market", img: "./markets/gombe/billiri.jpg", address: "Billiri Town, Billiri LGA" },
    { name: "Dukku Market", img: "./markets/gombe/dukku.jpg", address: "Dukku Town, Dukku LGA" },
    { name: "Gombe Main Market", img: "./markets/gombe/main.jpg", address: "Main Market Road, Gombe City" },
    { name: "Kaltungo Market", img: "./markets/gombe/kaltungo.jpg", address: "Kaltungo Town, Kaltungo LGA" },
    { name: "Kasuwar Waya Gombe", img: "./markets/gombe/waya.jpg", address: "Gombe City" },    
    { name: "Kuri Market", img: "./markets/gombe/kuri.jpg", address: "Yamaltu/Deba LGA" },
    { name: "Lapan Market", img: "./markets/gombe/lapan.jpg", address: "Lapan Town, Balanga LGA" },
    { name: "Nafada Market", img: "./markets/gombe/nafada.jpg", address: "Nafada Town, Nafada LGA" },
    { name: "Pindiga Market", img: "./markets/gombe/pindiga.jpg", address: "Pindiga Town, Akko LGA" },
    { name: "Talasse Market", img: "./markets/gombe/talasse.jpg", address: "Talasse Town, Balanga LGA" },
    { name: "Tudun Hatsi Market", img: "./markets/gombe/tudun-hatsi.jpg", address: "Kumo Town, Akko LGA" },
  ],

  Imo: [
    { name: "Afor Ogbe Market", img: "./markets/imo/afor-ogbe.jpg", address: "Ahiazu Mbaise" },
    { name: "Anhara Market", img: "./markets/imo/anhara.jpg", address: "Isiala Mbano" },
    { name: "Christ Church Market", img: "./markets/imo/christ-church.jpg", address: "Owerri" },
    { name: "Eke Onuwa Market", img: "./markets/imo/eke-onuwa.jpg", address: "Owerri" },
    { name: "Eke Ukwu Owerri Market", img: "./markets/imo/ekeukwu.jpg", address: "Owerri" },
    { name: "Ekpe Ikpa Market", img: "./markets/imo/ekpeikpa.jpg", address: "Isinweke" },
    { name: "International Market", img: "./markets/imo/international.jpg", address: "Orlu" },
    { name: "Okigwe Market", img: "./markets/imo/okigwe.jpg", address: "Okigwe" },
    { name: "Orie Agu Nsu Market", img: "./markets/imo/orie-agu.jpg", address: "Ehime Mbano" },
    { name: "Orlu Main Market", img: "./markets/imo/orlu-main.jpg", address: "Orlu" },
    { name: "Owerri Market", img: "./markets/imo/owerri.jpg", address: "Owerri" },
    { name: "Relief Market", img: "./markets/imo/relief.jpg", address: "Owerri" },
  ],

  Jigawa: [
    { name: "Babura Market", img: "./markets/jigawa/babura.jpg", address: "Babura" },
    { name: "Birnin Kudu Market", img: "./markets/jigawa/birnin-kudu.jpeg", address: "Birnin Kudu town" },
    { name: "Dutse Market", img: "./markets/jigawa/dutse.jpeg", address: "Dutse" },
    { name: "Garki Market", img: "./markets/jigawa/garki.jpeg", address: "Garki" },
    { name: "Gwaram Market", img: "./markets/jigawa/gwaram.jpeg", address: "Gwaram town" },
    { name: "Gwiwa Market", img: "./markets/jigawa/gwiwa.jpeg", address: "Gwiwa" },
    { name: "Hadejia Market", img: "./markets/jigawa/hadejia.jpeg", address: "Hadejia town" },
    { name: "Jahun Market", img: "./markets/jigawa/jahun.jpeg", address: "Jahun town" },
    { name: "Kafin Hausa Market", img: "./markets/jigawa/kafin-hausa.jpeg", address: "Kafin Hausa town" },
    { name: "Kazaure Market", img: "./markets/jigawa/kazaure.jpeg", address: "Kazaure town" },
    { name: "Maigatari Market", img: "./markets/jigawa/maigatari.jpeg", address: "Maigatari town" },
    { name: "Ringim Market", img: "./markets/jigawa/ringim.jpeg", address: "Ringim town" },
  ],

  Kaduna: [
    { name: "Birnin Gwari Market", img: "./markets/kaduna/birnin-gwari.jpeg", address: "Birnin Gwari town" },
    { name: "Giwa Market", img: "./markets/kaduna/giwa.jpeg", address: "Giwa town" },
    { name: "Hunkuyi Market", img: "./markets/kaduna/hunkuyi.jpg", address: "Hunkuyi town" },
    { name: "Ikara Market", img: "./markets/kaduna/ikara.jpeg", address: "Ikara town" },
    { name: "Kafanchan Market", img: "./markets/kaduna/kafanchan.jpeg", address: "Kafanchan town" },
    { name: "Kawo Market", img: "./markets/kaduna/kawo.jpeg", address: "Kawo area, Kaduna city" },
    { name: "Kujama Market", img: "./markets/kaduna/kujama.jpg", address: "Kujama town" },
    { name: "Makarfi Market", img: "./markets/kaduna/makarfi.jpg", address: "Makarfi town" },
    { name: "Pambegua Market", img: "./markets/kaduna/pambegua.jpeg", address: "Pambegua town" },
    { name: "Sabo Market", img: "./markets/kaduna/sabo.jpg", address: "Sabo area, Kaduna city" },
    { name: "Saminaka Market", img: "./markets/kaduna/saminaka.jpg", address: "Saminaka town" },
  ],

  Kano: [
    { name: "Bichi Market", img: "./markets/kano/bichi.jpg", address: "Bichi town" },
    { name: "Dawanau Market", img: "./markets/kano/dawanau.jpg", address: "Dawakin Tofa LGA" },
    { name: "Doka Market", img: "./markets/kano/doka.jpg", address: "Tofa LGA" },
    { name: "Gezawa Market", img: "./markets/kano/gezawa.jpg", address: "Gezawa town" },
    { name: "Gwarzo Market", img: "./markets/kano/gwarzo.jpg", address: "Gwarzo town" },
    { name: "Kofar Wambai Market", img: "./markets/kano/kofar-wambai.jpg", address: "Kano city" },
    { name: "Kura Market", img: "./markets/kano/kura.jpg", address: "Court Road, Fagge" },
    { name: "Kurmi Market", img: "./markets/kano/kurmi.jpg", address: "Kano city" },
    { name: "Rano Market", img: "./markets/kano/rano.jpg", address: "Rano town" },
    { name: "Sabon Gari Market", img: "./markets/kano/sabon-gari.jpg", address: "Sabon Gari area, Kano city" },
    { name: "Singer Market", img: "./markets/kano/singer.jpg", address: "Kano city" },
    { name: "Tarauni Market", img: "./markets/kano/tarauni.jpg", address: "Tarauni area, Kano city" },
    { name: "Ungogo Market", img: "./markets/kano/ungogo.jpg", address: "Ungogo town" },
    { name: "Wudil Market", img: "./markets/kano/wudil.jpg", address: "Wudil town" },
    { name: "Yankaba Market", img: "./markets/kano/yankaba.jpg", address: "Yankaba area, Kano city" },
  ],

  Katsina: [
    { name: "Bakori Market", img: "./markets/katsina/bakori.jpg", address: "Bakori Town" },
    { name: "Batsari Market", img: "./markets/katsina/batsari.jpg", address: "Batsari Town" },
    { name: "Dandume Market", img: "./markets/katsina/dandume.jpg", address: "Dandume Town" },
    { name: "Danja Market", img: "./markets/katsina/danja.jpg", address: "Danja Town" },
    { name: "Dutsin-Ma Market", img: "./markets/katsina/dutsin-ma.jpg", address: "Dutsin-Ma Town" },
    { name: "Funtua Market", img: "./markets/katsina/funtua.jpg", address: "Funtua Town" },
    { name: "Jibia Border Market", img: "./markets/katsina/jibia.jpg", address: "Jibia Town" },
    { name: "Kafur Market", img: "./markets/katsina/kafur.jpg", address: "Kafur Town" },
    { name: "Kankara Market", img: "./markets/katsina/kankara.jpg", address: "Kankara Town" },
    { name: "Katsina Central Market", img: "./markets/katsina/central.jpg", address: "Katsina City" },
    { name: "Maiadua International Market", img: "./markets/katsina/maiadua.jpg", address: "Maiadua Town" },
    { name: "Mashi Market", img: "./markets/katsina/mashi.jpeg", address: "Mashi Town" },
    { name: "Sheme Market", img: "./markets/katsina/sheme.jpg", address: "Sheme Town" },
  ],

  Kebbi: [
    { name: "Aliero Market", img: "./markets/kebbi/aliero.jpg", address: "Aliero" },
    { name: "Argungu Central Market", img: "./markets/kebbi/argungu.jpg", address: "Argungu" },
    { name: "Augie Market", img: "./markets/kebbi/augie.jpg", address: "Augie" },
    { name: "Besse Market", img: "./markets/kebbi/besse.jpeg", address: "Besse" },
    { name: "Bunza Market", img: "./markets/kebbi/bunza.jpg", address: "Bunza" },
    { name: "Central Market", img: "./markets/kebbi/central.jpg", address: "Birnin Kebbi" },
    { name: "Dodoru Market", img: "./markets/kebbi/dodoru.jpg", address: "Dodoru" },
    { name: "Gwandu Market", img: "./markets/kebbi/gwandu.jpg", address: "Gwandu" },
    { name: "Jega Market", img: "./markets/kebbi/jega.jpg", address: "Jega" },
    { name: "Kalgo Market", img: "./markets/kebbi/kalgo.jpg", address: "Kalgo" },
    { name: "Koko Market", img: "./markets/kebbi/koko.jpg", address: "Koko" },
    { name: "Maiyama Market", img: "./markets/kebbi/maiyama.jpg", address: "Maiyama" },
    { name: "Suru Market", img: "./markets/kebbi/suru.jpg", address: "Suru" },
    { name: "Yauri Market", img: "./markets/kebbi/yauri.jpg", address: "Yauri" },
    { name: "Zuru Market", img: "./markets/kebbi/zuru.jpg", address: "Zuru" },
  ],

  Kogi: [
    { name: "Aiyegunle Market", img: "./markets/kogi/aiyegunle.jpeg", address: "Aiyegunle" },
    { name: "Ajaka Main Market", img: "./markets/kogi/ajaka.jpg", address: "Ajaka" },
    { name: "Aliade Main Market", img: "./markets/kogi/aliade.jpeg", address: "Aliade" },
    { name: "Ankpa Main Market", img: "./markets/kogi/ankpa.jpeg", address: "Ankpa" },
    { name: "Anyigba Market", img: "./markets/kogi/anyigba.jpg", address: "Anyigba" },
    { name: "Idah Main Market", img: "./markets/kogi/idah.jpg", address: "Idah" },
    { name: "Isanlu Market", img: "./markets/kogi/isanlu.jpeg", address: "Isanlu" },
    { name: "Kabba Market", img: "./markets/kogi/kabba.jpg", address: "Kabba" },
    { name: "Lokoja International Market", img: "./markets/kogi/lokoja-international.jpg", address: "Lokoja" },
    { name: "Lokoja Old Market", img: "./markets/kogi/lokoja-old.jpeg", address: "Lokoja" },
    { name: "Obangede Market", img: "./markets/kogi/obangede.jpeg", address: "Obangede" },
    { name: "Ofu Market", img: "./markets/kogi/ofu.jpeg", address: "Ofu" },
    { name: "Ogori Market", img: "./markets/kogi/ogori.jpeg", address: "Ogori" },
    { name: "Okene Main Market", img: "./markets/kogi/okene.jpg", address: "Okene" },
    { name: "Uga Market", img: "./markets/kogi/uga.jpeg", address: "Uga" },
  ],

  Kwara: [
    { name: "Aremu Market", img: "./markets/kwara/aremu.jpg", address: "Ilorin South" },
    { name: "Isale Oja Market", img: "./markets/kwara/isale-oja.jpg", address: "Ilorin East" },
    { name: "Jebba Market", img: "./markets/kwara/jebba.png", address: "Jebba" },
    { name: "Offa Central Market", img: "./markets/kwara/offa-central.jpg", address: "Offa" },
    { name: "Oja Agbo Market", img: "./markets/kwara/oja-agbo.jpg", address: "Ilorin" },
    { name: "Oja Aje Market", img: "./markets/kwara/oja-aje.jpg", address: "Ilorin" },
    { name: "Oja Ipata Market", img: "./markets/kwara/oja-ipata.jpg", address: "Ilorin" },
    { name: "Oja Oba Market", img: "./markets/kwara/oja-oba.jpg", address: "Ilorin" },
    { name: "Oja Oke Market", img: "./markets/kwara/oja-oke.jpg", address: "Ilorin" },
    { name: "Oja Tuntun Market", img: "./markets/kwara/oja-tuntun.jpg", address: "Ilorin" },
    { name: "Omu-Aran Main Market", img: "./markets/kwara/omu-aran.jpg", address: "Omu-Aran" },
    { name: "Sabo Market", img: "./markets/kwara/sabo.jpg", address: "Ilorin" },
  ],

  Lagos: [
    { name: "Agbalata Market", img: "./markets/lagos/agbalata.jpg", address:"Badagry" },
    { name: "Agboju Market", img: "./markets/lagos/agboju.jpg", address:"Festac Town" },
    { name: "Agege Market", img: "./markets/lagos/agege.jpg", address:"Agege" },
    { name: "Ajah Market", img: "./markets/lagos/ajah.jpg", address:"Ajah" },
    { name: "Alaba Market", img: "./markets/lagos/alaba.jpeg", address:"Alaba" },
    { name: "Aratumi Market", img: "./markets/lagos/aratumi.jpg", address:"Ojo" },
    { name: "Balogun Market", img: ".yy[[/markets/lagos/balogun.jpg", address:"Lagos Island" },
    { name: "Bar Beach Market", img: "./markets/lagos/barbeach.jpg", address:"Elegushi" },
    { name: "Computer Village", img: "./markets/computervillage.jpg", address:"Computer Village" },
    { name: "Daleko Market", img: "./markets/lagos/daleko.png", address:"Mushin" },
    { name: "Idumota Market", img: "./markets/lagos/idumota.jpg", address:"Idumota" },
    { name: "Ikotun Market", img: "./markets/lagos/ikotun.jpg", address:"Ikotun" },
    { name: "Ladipo Market", img: "./markets/lagos/ladipo.jpg", address:"Ladipo" },
    { name: "Lekki Market", img: "./markets/lagos/lekki.webp", address:"Lekki Penninsula" },
    { name: "Mile 12 Market", img: "./markets/lagos/BodijaMarket.jpg", address:"Ikotun Ketu" },
    { name: "Mushin Market", img: "./markets/lagos/mushin.jpg", address:"Mushin" },
    { name: "Oniru New Market", img: "./markets/lagos/oniru.webp", address:"Maroko Road" },
    { name: "Oshodi Market", img: "./markets/lagos/oshodi.jpg", address:"Oshodi" },
    { name: "Oyingbo Market", img: "./markets/lagos/oyingbo.jpg", address:"Ebute Metta" },
  ],

  Nasarawa: [
    { name: "Agon Gudi Market", img: "./markets/nasarawa/agon-gudi.jpg", address: "Shabu, Kokona Local Government Area, Nasarawa State" },
    { name: "Akwanga Market", img: "./markets/nasarawa/akwanga.jpg", address: "Akwanga, Nasarawa State" },
    { name: "Doma Market", img: "./markets/nasarawa/doma.jpg", address: "Doma, Nasarawa State" },
    { name: "Kasuwan Lafiya", img: "./markets/nasarawa/kasuwan-lafiya.jpg", address: "Lafia, Nasarawa State" },
    { name: "Karu Market", img: "./markets/nasarawa/karu.jpg", address: "Karu, Nasarawa State" },
    { name: "Keana Market", img: "./markets/nasarawa/keana.jpg", address: "Keana, Nasarawa State" },
    { name: "Keffi Market", img: "./markets/nasarawa/keffi.jpg", address: "Keffi, Nasarawa State" },
    { name: "Mada Station Market", img: "./markets/nasarawa/mada-station.jpg", address: "Nasarawa Eggon, Nasarawa State" },
    { name: "Mararaba Market", img: "./markets/nasarawa/mararaba.jpg", address: "Mararaba, Nasarawa State" },
    { name: "Masaka Market", img: "./markets/nasarawa/masaka.jpg", address: "Masaka, Karu Local Government Area, Nasarawa State" },
    { name: "Muhammadu Buhari International Market", img: "./markets/nasarawa/muhammadu-buhari-intl.jpg", address: "New Karu, Nasarawa State" },
    { name: "Nasarawa Eggon Market", img: "./markets/nasarawa/nasarawa-eggon.jpg", address: "Nasarawa Eggon, Nasarawa State" },
    { name: "Nasarawa Toto Market", img: "./markets/nasarawa/nasarawa-toto.jpg", address: "Toto Local Government Area, Nasarawa State" },
    { name: "Obi Market", img: "./markets/nasarawa/obi.jpg", address: "Obi, Nasarawa State" },
    { name: "Wamba Market", img: "./markets/nasarawa/wamba.jpg", address: "Wamba, Nasarawa State" },
  ],

  Niger: [
    { name: "Agaie Market", img: "./markets/niger/agaie.jpg", address: "Agaie, Niger State" },
    { name: "Etsu Musa Market", img: "./markets/niger/bida.jpg", address: "Bida, Niger State" },
    { name: "Gawu Babangida Market", img: "./markets/niger/gawu.jpg", address: "Gawu Babangida, Niger State" },
    { name: "Kagara Market", img: "./markets/niger/kagara.jpg", address: "Kagara, Niger State" },
    { name: "Kontagora Market", img: "./markets/niger/kontagora.jpg", address: "Kontagora, Niger State" },
    { name: "Lapai Market", img: "./markets/niger/lapai.jpg", address: "Lapai, Niger State" },
    { name: "Minna Central Market", img: "./markets/niger/minna-central.jpg", address: "Minna, Niger State" },
    { name: "Mokwa Market", img: "./markets/niger/mokwa.jpg", address: "Mokwa, Niger State" },
    { name: "New Bussa Market", img: "./markets/niger/new-bussa.jpg", address: "New Bussa, Niger State" },
    { name: "Paiko Market", img: "./markets/niger/paiko.jpg", address: "Paiko, Niger State" },
    { name: "Rijau Market", img: "./markets/niger/rijau.jpg", address: "Rijau, Niger State" },
    { name: "Suleja Market", img: "./markets/niger/suleja.jpeg", address: "Suleja, Niger State" },
    { name: "Tegina Market", img: "./markets/niger/tegina.jpg", address: "Tegina, Niger State" },
    { name: "Wushishi Market", img: "./markets/niger/wushishi.jpg", address: "Wushishi, Niger State" },
    { name: "Zungeru Market", img: "./markets/niger/zungeru.jpg", address: "Zungeru, Niger State" },
  ],

  Ogun: [
    { name: "Adire Market", img: "./markets/ogun/adire.jpg", address:"Sapon, Abeokuta" },
    { name: "Ago Iwoye Market", img: "./markets/ogun/ago-iwoye.jpg", address:"Ago Iwoye, Ijebu North" },
    { name: "Ifo Market", img: "./markets/ogun/ifo.jpg", address:"Ifo Town" },
    { name: "Ijebu Ode Market", img: "./markets/ogun/ijebu-ode.jpg", address:"Ijebu Ode Town" },
    { name: "Ijoko Market", img: "./markets/ogun/ijoko.jpg", address:"Ijoko, Ado-Odo/Ota" },
    { name: "Ilaro Market", img: "./markets/ogun/ilaro.jpg", address:"Ilaro Town" },
    { name: "Kuto Market", img: "./markets/ogun/kuto.jpg", address:"Kuto, Abeokuta" },
    { name: "Lafenwa Market", img: "./markets/ogun/lafenwa.jpg", address:"Lafenwa, Abeokuta" },
    { name: "Lusada Market", img: "./markets/ogun/lusada.jpg", address:"Agbara, Ogun" },
    { name: "Obantoko Market", img: "./markets/ogun/obantoko.jpg", address:"Obantoko, Abeokuta" },
    { name: "Oja Odan Market", img: "./markets/ogun/oja-odan.jpg", address:"Oja Odan, Yewa North" },
    { name: "Owode Market", img: "./markets/ogun/owode.jpg", address:"Owode, Yewa South" },
    { name: "Sagamu Market", img: "./markets/ogun/sagamu.jpg", address:"Sagamu Town" },
    { name: "Sango Ota Market", img: "./markets/ogun/ota.jpg", address:"Sango Ota, Ado-Odo/Ota" },
  ],

  Ondo: [
    { name: "Agadagba Market", img: "./markets/ondo/agadagba.jpg", address:"Agadagba, Ese-Odo" },
    { name: "Bolorunduro Market", img: "./markets/ondo/bolorunduro.jpg", address:"Bolorunduro, Ondo East" },
    { name: "Idanre Market", img: "./markets/ondo/idanre.jpg", address:"Idanre" },
    { name: "Ifon Market", img: "./markets/ondo/ifon.jpg", address:"Ifon, Ose LGA" },
    { name: "Igbokoda Market", img: "./markets/ondo/igbokoda.jpg", address:"Igbokoda, Ilaje" },
    { name: "Ikare Akoko Market", img: "./markets/ondo/ikare.jpg", address:"Ikare Akoko" },
    { name: "Irele Market", img: "./markets/ondo/irele.jpg", address:"Irele" },
    { name: "Isikan Market", img: "./markets/ondo/isikan.jpeg", address:"Akure" },
    { name: "Oja Oba Market", img: "./markets/ondo/oja-oba.jpg", address:"Akure" },
    { name: "Oja Oshodi Market", img: "./markets/ondo/oja-oshodi.jpg", address:"Ondo Town" },
    { name: "Oja Owo Market", img: "./markets/ondo/oja-owo.jpg", address:"Owo" },
    { name: "Ore Market", img: "./markets/ondo/ore.jpg", address:"Ore, Odigbo" },
    { name: "Shasha Market", img: "./markets/ondo/shasha.jpg", address:"Akure" },
    { name: "Supare Market", img: "./markets/ondo/supare.jpg", address:"Supare Akoko" },
  ],

  Osun: [
    { name: "Alekuwodo Market", img: "./markets/osun/alekuwodo.jpg", address:"Osogbo" },
    { name: "Atakumosa Market", img: "./markets/osun/atakumosa.jpg", address:"Ilesa" },
    { name: "Erin Osun Market", img: "./markets/osun/erin-osun.jpg", address:"Erin-Osun" },
    { name: "Gbongan Market", img: "./markets/osun/gbongan.jpg", address:"Gbongan" },
    { name: "Ife Central Market", img: "./markets/osun/ife-central.jpg", address:"Ile-Ife" },
    { name: "Igbona Market", img: "./markets/osun/igbona.jpg", address:"Osogbo" },
    { name: "Ikirun Market", img: "./markets/osun/ikirun.jpg", address:"Ikirun" },
    { name: "Ila Orangun Market", img: "./markets/osun/ila-orangun.jpg", address:"Ila-Orangun" },
    { name: "Odo Ori Market", img: "./markets/osun/odo-ori.jpg", address:"Iwo" },
    { name: "Oja Ejigbo Market", img: "./markets/osun/ejigbo.jpeg", address:"Ejigbo" },
    { name: "Oja Oba Market", img: "./markets/osun/oja-oba.jpg", address:"Osogbo" },
    { name: "Oja Sekona Market", img: "./markets/osun/sekona.jpg", address:"Sekona" },
    { name: "Oja Timi Market", img: "./markets/osun/oja-timi.jpg", address:"Ede" },
    { name: "Okuku Market", img: "./markets/osun/okuku.jpg", address:"Okuku" },
    { name: "Owode Ede Market", img: "./markets/osun/owode-ede.jpg", address:"Ede" },
  ],

  Oyo: [
    { name: "Agbeni Market", img: "./markets/oyo/agbeni.jpg", address: "Ibadan, Oyo State" },
    { name: "Aleshinloye Market", img: "./markets/oyo/aleshinloye.jpg", address: "Ibadan, Oyo State" },
    { name: "Apata Market", img: "./markets/oyo/apata.jpg", address: "Ibadan, Oyo State" },
    { name: "Beere Market", img: "./markets/oyo/beere.jpg", address: "Ibadan, Oyo State" },
    { name: "Bodija Market", img: "./markets/BodijaMarket.jpg", address: "Ibadan, Oyo State" },
    { name: "Dugbe Market", img: "./markets/oyo/dugbe.jpg", address: "Ibadan, Oyo State" },
    { name: "Gbagi International Market", img: "./markets/oyo/gbagi-international.jpg", address: "Ibadan, Oyo State" },
    { name: "Iseyin Market", img: "./markets/oyo/iseyin.jpg", address: "Iseyin, Oyo State" },
    { name: "Iso Adiye Market", img: "./markets/oyo/iso-adiye.jpg", address: "Ibadan, Oyo State" },
    { name: "New Waso Market", img: "./markets/oyo/new-waso.jpg", address: "Ibadan, Oyo State" },
    { name: "Ogunpa Market", img: "./markets/oyo/ogunpa.jpg", address: "Ibadan, Oyo State" },
    { name: "Oja Oba Market", img: "./markets/oyo/oja-oba.jpg", address: "Ibadan, Oyo State" },
    { name: "Oje Market", img: "./markets/oyo/oje.jpg", address: "Ibadan, Oyo State" },
    
  ],

  Plateau: [
    { name: "Abattoir Market", img: "./markets/plateau/abattoir.jpg", address: "Jos, Plateau State" },
    { name: "Barkin Ladi Market", img: "./markets/plateau/barkin-ladi.jpg", address: "Barkin Ladi, Plateau State" },
    { name: "Bassa Market", img: "./markets/plateau/bassa.jpg", address: "Bassa, Plateau State" },
    { name: "Building Materials Market", img: "./markets/plateau/building-materials.jpg", address: "Jos, Plateau State" },
    { name: "Farmer's Market", img: "./markets/plateau/farmers.jpg", address: "Jos, Plateau State" },
    { name: "Gada Biu Market", img: "./markets/plateau/gada-biu.jpg", address: "Jos, Plateau State" },
    { name: "Katako Market", img: "./markets/plateau/katako.jpg", address: "Jos, Plateau State" },
    { name: "Mangu Market", img: "./markets/plateau/mangu.jpg", address: "Mangu, Plateau State" },
    { name: "Pankshin Market", img: "./markets/plateau/pankshin.jpg", address: "Pankshin, Plateau State" },
    { name: "Potatoes Market", img: "./markets/plateau/potatoes.jpg", address: "Bokkos LGA, Plateau State" },
    { name: "Rukuba Road Market", img: "./markets/plateau/rukuba-road.jpg", address: "Jos, Plateau State" },
    { name: "Shendam Market", img: "./markets/plateau/shendam.jpg", address: "Shendam, Plateau State" },
    { name: "Terminus Market (Jos Main Market)", img: "./markets/plateau/terminus.jpg", address: "Jos, Plateau State" },
  ],

  Rivers: [
    { name: "Borokiri Market", img: "./markets/rivers/borokiri.jpg", address: "Borokiri, Port Harcourt, Rivers State" },
    { name: "Choba Market", img: "./markets/rivers/choba.jpg", address: "Choba, Port Harcourt, Rivers State" },
    { name: "Creek Road Market", img: "./markets/rivers/creek-road.jpg", address: "Creek Road, Port Harcourt, Rivers State" },
    { name: "Elelenwo Market", img: "./markets/rivers/elelenwo.jpg", address: "Elelenwo, Port Harcourt, Rivers State" },
    { name: "Fruit Garden Market", img: "./markets/rivers/fruit-garden.jpg", address: "D-Line, Port Harcourt, Rivers State" },
    { name: "Igwuruta Market", img: "./markets/rivers/igwuruta.jpg", address: "Igwuruta, Port Harcourt, Rivers State" },
    { name: "Iriebe Market", img: "./markets/rivers/iriebe.jpg", address: "Iriebe, Port Harcourt, Rivers State" },
    { name: "Marine Base Market", img: "./markets/rivers/marine-base.jpg", address: "Marine Base, Port Harcourt, Rivers State" },
    { name: "Mbiama Market", img: "./markets/rivers/mbiama.jpg", address: "Mbiama, Rivers State" },
    { name: "Mile One Market", img: "./markets/rivers/mile-one.jpeg", address: "Diobu, Port Harcourt, Rivers State" },
    { name: "Nchia-Eleme Market", img: "./markets/rivers/nchia-eleme.jpg", address: "Nchia, Eleme, Rivers State" },
    { name: "Ogbunabali Market", img: "./markets/rivers/ogbunabali.jpg", address: "Ogbunabali, Port Harcourt, Rivers State" },
    { name: "Oil Mill Market", img: "./markets/rivers/oil-mill.jpg", address: "Eleme Junction, Aba Road, Port Harcourt, Rivers State" },
    { name: "Old Rumuodogo Market", img: "./markets/rivers/old-rumuodogo.jpg", address: "Emuoha, Rivers State" },
    { name: "Rumuokoro Market", img: "./markets/rivers/rumuokoro.jpg", address: "Rumuokoro, Port Harcourt, Rivers State" },
  ],

  Sokoto: [
    { name: "Bodinga Market", img: "./markets/sokoto/bodinga.jpg", address: "Bodinga" },
    { name: "Dange Market", img: "./markets/sokoto/dange.jpg", address: "Dange" },
    { name: "Goronyo Market", img: "./markets/sokoto/goronyo.jpg", address: "Goronyo" },
    { name: "Gwadabawa Market", img: "./markets/sokoto/gwadabawa.jpg", address: "Gwadabawa" },
    { name: "Illela Market", img: "./markets/sokoto/illela.jpg", address: "Illela" },
    { name: "Kebbe Market", img: "./markets/sokoto/kebbe.jpg", address: "Kebbe" },
    { name: "Kware Market", img: "./markets/sokoto/kware.jpg", address: "Kware" },
    { name: "Old Market", img: "./markets/sokoto/old.jpg", address: "Sokoto" },
    { name: "Rabah Market", img: "./markets/sokoto/rabah.jpg", address: "Rabah" },
    { name: "Shagari Market", img: "./markets/sokoto/shagari.jpg", address: "Shagari" },
    { name: "Silame Market", img: "./markets/sokoto/silame.jpg", address: "Silame" },
    { name: "Tambuwal Market", img: "./markets/sokoto/tambuwal.jpg", address: "Tambuwal" },
    { name: "Tureta Market", img: "./markets/sokoto/tureta.jpg", address: "Tureta" },
    { name: "Wurno Market", img: "./markets/sokoto/wurno.jpg", address: "Wurno" },
  ],

  Taraba: [
    { name: "ATC Market", img: "./markets/taraba/atc.jpg", address: "Ardo-Kola LGA, Taraba State" },
    { name: "Bali Market", img: "./markets/taraba/bali.jpg", address: "Bali Town, Bali LGA, Taraba State" },
    { name: "Garin Mallum Market", img: "./markets/taraba/garin-mallum.jpg", address: "Garin Mallum Town, Ardo-Kola LGA, Taraba State" },
    { name: "Gassol Market", img: "./markets/taraba/gassol.jpg", address: "Gassol Town, Gassol LGA, Taraba State" },
    { name: "Gomu Main Market", img: "./markets/taraba/gomu.jpg", address: "Gomu Town, Taraba State" },
    { name: "Iware Market", img: "./markets/taraba/iware.jpg", address: "Iware Town, Ardo-Kola LGA, Taraba State" },
    { name: "Karim Lamido Market", img: "./markets/taraba/karim-lamido.jpg", address: "Karim Lamido Town, Karim Lamido LGA, Taraba State" },
    { name: "Kasuwan Lahadi Market", img: "./markets/taraba/kasuwan-lahadi.jpg", address: "Ardo-Kola LGA, Taraba State" },
    { name: "Mayo-Renewo Market", img: "./markets/taraba/mayo-renewo.jpg", address: "Mayo-Renewo Town, Ardo-Kola LGA, Taraba State" },
    { name: "Mile 6 Market", img: "./markets/taraba/mile-6.jpg", address: "Jalingo" },
    { name: "Pawas Central Market", img: "./markets/taraba/pawas.jpg", address: "Zing Town, Zing LGA, Taraba State" },
    { name: "Sardauna Market", img: "./markets/taraba/sardauna.jpg", address: "Sardauna Town, Sardauna LGA, Taraba State" },
    { name: "Sunkani Market", img: "./markets/taraba/sunkani.jpg", address: "Sunkani Town, Ardo-Kola LGA, Taraba State" },
    { name: "Takum Market", img: "./markets/taraba/takum.jpg", address: "Takum Town, Takum LGA, Taraba State" },
    { name: "Wukari Yam Market", img: "./markets/taraba/wukari.jpg", address: "Wukari Town, Wukari LGA, Taraba State" },
  ],

  Yobe: [
    { name: "Babban Tasha Market", img: "./markets/yobe/babban-tasha.jpeg", address: "Potiskum Town, Potiskum LGA, Yobe State" },
    { name: "Buni Yadi Market", img: "./markets/yobe/buni-yadi.jpg", address: "Buni Yadi Town, Gujba LGA, Yobe State" },
    { name: "Damaturu Market", img: "./markets/yobe/damaturu.jpg", address: "Damaturu Town, Damaturu LGA, Yobe State" },
    { name: "Dapchi Market", img: "./markets/yobe/dapchi.jpg", address: "Dapchi Town, Bursari LGA, Yobe State" },
    { name: "Gashua Market", img: "./markets/yobe/gashua.jpeg", address: "Gashua Town, Bade LGA, Yobe State" },
    { name: "Geidam Market", img: "./markets/yobe/geidam.jpg", address: "Geidam Town, Geidam LGA, Yobe State" },
    { name: "Gujba Market", img: "./markets/yobe/gujba.jpeg", address: "Gujba Town, Gujba LGA, Yobe State" },
    { name: "Jajimaji Market", img: "./markets/yobe/jajimaji.jpg", address: "Jajimaji Town, Karasuwa LGA, Yobe State" },
    { name: "Kukuwa Market", img: "./markets/yobe/kukuwa.jpeg", address: "Kukuwa Town, Gulani LGA, Yobe State" },
    { name: "Machina Market", img: "./markets/yobe/machina.jpeg", address: "Machina Town, Machina LGA, Yobe State" },
    { name: "Ngalda Market", img: "./markets/yobe/ngalda.jpeg", address: "Ngalda Town, Fika LGA, Yobe State" },
    { name: "NPN Market", img: "./markets/yobe/npn.jpeg", address: "Kasuwar NPN Area, Potiskum, Yobe State" },
    { name: "Potiskum Market", img: "./markets/yobe/potiskum.jpeg", address: "Potiskum Town, Potiskum LGA, Yobe State" },
    { name: "Sabon Gari Market", img: "./markets/yobe/sabon-gari.jpeg", address: "Damaturu Town, Damaturu LGA, Yobe State" },
  ],

  Zamfara: [
    { name: "Anka Market", img: "./markets/zamfara/anka.jpg", address: "Anka" },
    { name: "Bakura Market", img: "./markets/zamfara/bakura.jpg", address: "Bakura" },
    { name: "Bukkuyum Market", img: "./markets/zamfara/bukkuyum.jpg", address: "Bukkuyum" },
    { name: "Bungudu Market", img: "./markets/zamfara/bungudu.jpg", address: "Bungudu" },
    { name: "Chafe Market", img: "./markets/zamfara/chafe.jpg", address: "Chafe" },
    { name: "Danjibga Market", img: "./markets/zamfara/danjibga.jpg", address: "Danjibga" },
    { name: "Gummi Market", img: "./markets/zamfara/gummi.jpg", address: "Gummi" },
    { name: "Gusau Market", img: "./markets/zamfara/gusau.jpg", address: "Gusau" },
    { name: "Kaura Namoda Market", img: "./markets/zamfara/kaura-namoda.jpg", address: "Kaura Namoda" },
    { name: "Maradun Market", img: "./markets/zamfara/maradun.jpg", address: "Maradun" },
    { name: "Maru Market", img: "./markets/zamfara/maru.jpg", address: "Maru" },
    { name: "Shinkafi Market", img: "./markets/zamfara/shinkafi.jpg", address: "Shinkafi" },
    { name: "Talata Mafara Market", img: "./markets/zamfara/talata-mafara.jpg", address: "Talata Mafara" },
    { name: "Tsafe Market", img: "./markets/zamfara/tsafe.jpg", address: "Tsafe" },
    { name: "Zurmi Market", img: "./markets/zamfara/zurmi.jpg", address: "Zurmi" },
  ],
};

module.exports = MARKETS; 
