const MARKETS = {
  Abia: [
    { name: "Ariaria International Market", img: "./markets/abia/ariaria.jpeg", address:"Aba, Abia" },
    { name: "Umuahia Main Market", img: "./markets/abia/umuahia.jpg", address:"Umuahia, Abia" },
    { name: "Ubakala Market", img: "./markets/abia/ubakala.jpg", address:"Ubakala, Abia" },
    { name: "Aba International Market", img: "./markets/abia/aba-international.png", address:"Aba, Abia" },
    { name: "Ohia Market", img: "./markets/abia/ohia.jpg", address:"Ohia, Abia" },
    { name: "Eziukwu Market", img: "./markets/abia/eziukwu.jpeg", address:"Eziukwu, Abia" },
    { name: "Ikwuano Market", img: "./markets/abia/ikwuano.jpg", address:"Ikwuano, Abia" },
    { name: "Oke Ikpe Market", img: "./markets/abia/okeikpe.jpg", address:"Okeikpe, Abia" },
    { name: "Uzuakoli Market", img: "./markets/abia/uzuakoli.jpeg", address:"Uzuakoli, abia" },
    { name: "Alaoji Market", img: "./markets/abia/alaoji.jpg", address:"Alaoji, Abia" },
    { name: "Umuocham Market", img: "./markets/abia/umuocham.jpeg", address:"Umuocham, Abia" },
    { name: "Oriendu Market", img: "./markets/abia/oriendu.jpeg", address:"Oriendu, Abia" },
    { name: "Ndiegoro Market", img: "./markets/abia/ndiegoro.jpg", address:"Ndiegoro, Abia" },
  ],

AkwaIbom: [
    { name: "Eket Fish Market", img: "./markets/akwa-ibom/eket-fish.jpg", address:"Eket, Akwa Ibom" },
    { name: "Eket Main Market", img: "./markets/akwa-ibom/eket-main.jpg", address:"Eket, Akwa Ibom" },
    { name: "Itam Market", img: "./markets/akwa-ibom/itam.jpeg", address:"Itam, Akwa Ibom" },
    { name: "Oron Fish Market", img: "./markets/akwa-ibom/oron-fish.jpeg", address:"Oron, Akwa Ibom" },
    { name: "Urua Akpan Ete Market", img: "./markets/akwa-ibom/urua-akpan-ete.jpeg", address:"Urua Akpan Ete, Akwa Ibom" }, 
    { name: "Ikot Abasi Main Market", img: "./markets/akwa-ibom/ikot-abasi.jpg", address:"Ikot Abasi, Akwa Ibom" },
    { name: "Ikono Main Market", img: "./markets/akwa-ibom/ikono.jpeg", address:"Ikono, Akwa Ibom" },
    { name: "Urua Ikono Market", img: "./markets/akwa-ibom/urua-ikono.jpeg", address:"Urua Ikono, Akwa Ibom" },
    { name: "Nto Edino Market", img: "./markets/akwa-ibom/ntoedino.jpeg", address:"Nto Edino, Akwa Ibom" },
    { name: "Etinan Main Market", img: "./markets/akwa-ibom/etinan.jpeg", address:"Etinan, Akwa Ibom" },
    { name: "Ikot Akpan Market", img: "./markets/akwa-ibom/ikot-akpan.jpg", address:"Ikot Akpan, Akwa Ibom" },
  ],

  Anambra: [
    { name: "Afor Igwe Market", img: "./markets/anambra/afor-igwe.jpg", address:"Afor Igwe, Anambra" },
    { name: "Amaenyi Market", img: "./markets/anambra/amaenyi.jpeg", address:"Amaenyi, Anambra" },
    { name: "Bridgehead Market", img: "./markets/anambra/bridgehead.jpg", address:"Bridgehead, Anambra" },
    { name: "Eke Amaobi Market", img: "./markets/anambra/ekeamaobi.jpg", address:"Eke Amaobi, Anambra" },
    { name: "Eke Awka Market", img: "./markets/anambra/ekeawka.jpeg", address:"Eke Awka, Anambra" },
    { name: "Eke Ekwulobia Market", img: "./markets/anambra/ekeekwulobia.jpeg", address:"Eke Ekwulobia, Anambra" },
    { name: "Eke Market", img: "./markets/anambra/eke.jpeg", address:"Eke Aguleri, Anambra" },
    { name: "Nkwo Ekwulobia Market", img: "./markets/anambra/nkwo-ekwulobia.jpg", address:"Nkwo Ekwulobia, Anambra" },
    { name: "Nkwo Nnewi Market", img: "./markets/anambra/nkwo-nnewi.jpeg", address:"Nkwo Nnewi, Anambra" },
    { name: "Nkwelle Market", img: "./markets/anambra/nkwelle.jpg", address:"Nkwelle, Anambra" },
    { name: "Nnewi Spare Parts Market", img: "./markets/anambra/nnewi-spareparts.png", address:"Nnewi, Anambra" },
    { name: "Ochanja Market", img: "./markets/anambra/ochanja.jpg", address:"Ochanja, Anambra" },
    { name: "Onitsha Main Market", img: "./markets/anambra/onitsha.jpg", address:"Onitsha, Anambra" },
    { name: "Relief Market", img: "./markets/anambra/relief.jpg", address:"Relief, Anambra" },
    { name: "Uru Market", img: "./markets/anambra/uru.jpg", address:"Uru, Anambra" },
  ],
  
  Bauchi: [
    { name: "Alkaleri Central Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Badara Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Bagel Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Bakin Kura Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Bogoro Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Central Market Bauchi", img: "./markets/BodijaMarket.jpg" },
    { name: "Dagu Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Lusa Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Magama Gumau Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Misau Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Muda Lawal Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Warji Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Wanka Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Wunti Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Yelwa Market", img: "./markets/BodijaMarket.jpg",},
    { name: "Yuli Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Zindi Market", img: "./markets/BodijaMarket.jpg" },
  ],

  Bayelsa: [
    { name: "Akassa Fish Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Aleibiri Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Amabulou Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Amassoma Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Anyama-Ogbia Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Brass Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Darazo Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Egwema Local Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ekeremor Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ekeki Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Kolo Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Oporoma Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Opolo Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ofoni Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Opu-Nembe Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Peretoru Local Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Sagbama Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Tombia Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Toru-Orua Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Twon Brass Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Yelwa Market", img: "./markets/BodijaMarket.jpg" },
  ],

  Benue: [
    { name: "Akaajime Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Enugu Road Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Gboko Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Gboko North Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Gboko South Market", img: "./markets/BodijaMarket.jpg" },
    { name: "GRA Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Katsina-Ala Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Makurdi Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Makurdi Modern Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Mbalagh Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Naka Road Market", img: "./markets/BodijaMarket.jpg" },
    { name: "North Bank Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ugbokolo Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Wurukum Market", img: "./markets/BodijaMarket.jpg" },
  ],

  Borno: [
    { name: "Baga Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Bama Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Bama Sunday Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Biu Central Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Biu Friday Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Biu Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Biu Motor Park Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Customs Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Gamboru Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Kadamari Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Kwanan Gashu'a Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Kwaya Kusar Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Maiduguri Main Market (Bama Road Market)", img: "./markets/BodijaMarket.jpg", },
    { name: "Ngamdu Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Old Maiduguri Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Wulgo Market", img: "./markets/BodijaMarket.jpg" },
  ],

  CrossRiver: [
    { name: "Akamkpa Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Akamkpa Timber Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Akpabuyo Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Bendeghe Ekiem Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Bekwarra Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Biase Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Biase Town Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Boki Agricultural Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Boki Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Danare Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ediba Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Etomi Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Igede Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Igede Weekly Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ikom Cattle Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ikom Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Iso-bendghe Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ugep Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ukpe Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ukelle Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Worji Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Yala Market", img: "./markets/BodijaMarket.jpg" },
  ],

  Lagos: [
    { name: "Alaba Market", img: "./markets/lagos/alaba.jpeg", address:"Alaba, Lagos" },
    { name: "Agbalata Market", img: "./markets/lagos/agbalata.jpg", address:"Badagry, Lagos" },
    { name: "Ajah Market", img: "./markets/lagos/ajah.jpg", address:"Ajah, Lagos" },
    { name: "Aratumi Market", img: "./markets/lagos/aratumi.jpg", address:"Ojo, Lagos" },
    { name: "Balogun Market", img: "./markets/lagos/balogun.jpg", address:"Lagos Island, Lagos" },
    { name: "Bar Beach Market", img: "./markets/lagos/barbeach.jpg", address:"Elegushi, Victoria Island, Lagos" },
    { name: "Computer Village", img: "./markets/computervillage.jpg", address:"Computer Village, Lagos Island" },
    { name: "Ikotun Market", img: "./markets/lagos/ikotun.jpg", address:"Ikotun, Lagos" },
    { name: "Idumota Market", img: "./markets/lagos/idumota.jpg", address:"Idumota, Lagos Island" },
    { name: "Ladipo Market", img: "./markets/lagos/ladipo.jpg", address:"Ladipo, Lagos" },
    { name: "Lekki Market", img: "./markets/lagos/lekki.webp", address:"Lekki Penninsula, Lagos" },
    { name: "Agboju Market", img: "./markets/lagos/agboju.jpg", address:"Festac Town, Lagos" },
    { name: "Daleko Market", img: "./markets/lagos/daleko.png", address:"Mushin, Lagos" },
    { name: "Mushin Market", img: "./markets/lagos/mushin.jpg", address:"Mushin, Lagos" },
    { name: "Oyingbo Market", img: "./markets/lagos/oyingbo.jpg", address:"Ebute Metta, Lagos" },
    { name: "Mile 12 Market", img: "./markets/lagos/BodijaMarket.jpg", address:"Ikotun Ketu, Lagos" },
    { name: "Oniru New Market", img: "./markets/lagos/oniru.webp", address:"Maroko Road, Lagos" },
    { name: "Oshodi Market", img: "./markets/lagos/oshodi.jpg", address:"Oshodi, Lagos" },
    { name: "Agege Market", img: "./markets/lagos/agege.jpg", address:"Agege, Lagos" },
  ],

  Oyo: [
    { name: "Aleshinloye Market", img: "./markets/oyo/aleshinloye.jpg", address:"Aleshinloye area, Ibadan" },
    { name: "Apata Market", img: "./markets/oyo/apata.jpg", address:"Apata area, Ibadan" },
    { name: "Beere Market", img: "./markets/oyo/beere.jpg", address:"Beere area, Ibadan" },
    { name: "Bodija Market", img: "./markets/BodijaMarket.jpg", address:"Bodija, Ibadan North, Ibadan" },
    { name: "Dugbe Market", img: "./markets/oyo/dugbe.jpg", address:"Central business district, Ibadan" },
    { name: "Gbagi International Market", img: "./markets/oyo/gbagi-international.jpg", address:"Ibadan-Ife Road, Ibadan" },
    { name: "Iseyin Market", img: "./markets/oyo/iseyin.jpg", address:"Iseyin Town" },
    { name: "Iso Adiye Market", img: "./markets/oyo/iso-adiye.jpg", address:"Ibadan" },
    { name: "New Waso Market", img: "./markets/oyo/new-waso.jpg", address:"Ogbomoso North, Ogbomoso" },
    { name: "Oja Oba Market", img: "./markets/oyo/oja-oba.jpg", address:"Near the Alaafin's palace, Oyo Town" },
    { name: "Oje Market", img: "./markets/oyo/oje.jpg", address:"Oje area, Ibadan" },
    { name: "Ojoo Market", img: "./markets/oyo/ojoo.jpg", address:"Ojoo area, Ibadan" },
    { name: "Ogunpa Market", img: "./markets/oyo/ogunpa.jpg", address:"Dugbe Alawo area, Ibadan" },
    { name: "Oranyan Market", img: "./markets/oyo/oranyan.jpg", address:"Oranyan area, Ibadan" },
    { name: "Sango Market", img: "./markets/oyo/sango.jpg", address:"Sango Area, Ibadan" },
  ],

  Ogun: [
    { name: "Adire Market", img: "./markets/ogun/adire.jpg", address:"Sapon, Abeokuta" },
    { name: "Ago Iwoye Market", img: "./markets/ogun/ago-iwoye.jpg", address:"Ago Iwoye, Ijebu North" },
    { name: "Ifo Market", img: "./markets/ogun/ifo.jpg", address:"Ifo Town" },
    { name: "Ijebu Ode Market", img: "./markets/ogun/ijebu-ode.jpg", address:"Ijebu Ode Town" },
    { name: "Ijoko Market", img: "./markets/ogun/ijoko.jpg", address:"Ijoko, Ado-Odo/Ota" },
    { name: "Ilaro Market", img: "./markets/ogun/ilaro.jpg", address:"Ilaro Town" },
    { name: "Kuto Market", img: "./markets/ogun/kuto.jpg", address:"Kuto, Abeokuta" },
    { name: "Lafenwa Market", img: "./markets/ogun/lafenwa.jpg", address:"Lafenwa, Abeokuta" },
    { name: "Lusada Market", img: "./markets/ogun/lusada.jpg", address:"Agbara, Ogun" },
    { name: "Obantoko Market", img: "./markets/ogun/obantoko.jpg", address:"Obantoko, Abeokuta" },
    { name: "Oja Odan Market", img: "./markets/ogun/oja-odan.jpg", address:"Oja Odan, Yewa North" },
    { name: "Owode Market", img: "./markets/ogun/owode.jpg", address:"Owode, Yewa South" },
    { name: "Sagamu Market", img: "./markets/ogun/sagamu.jpg", address:"Sagamu Town" },
    { name: "Sango Ota Market", img: "./markets/ogun/ota.jpg", address:"Sango Ota, Ado-Odo/Ota" },
  ],

  Ondo: [
    { name: "Agadagba Market", img: "./markets/ondo/agadagba.jpg", address:"Agadagba, Ese-Odo" },
    { name: "Bolorunduro Market", img: "./markets/ondo/bolorunduro.jpg", address:"Bolorunduro, Ondo East" },
    { name: "Idanre Market", img: "./markets/ondo/idanre.jpg", address:"Idanre" },
    { name: "Ifon Market", img: "./markets/ondo/ifon.jpg", address:"Ifon, Ose LGA" },
    { name: "Igbokoda Market", img: "./markets/ondo/igbokoda.jpg", address:"Igbokoda, Ilaje" },
    { name: "Ikare Akoko Market", img: "./markets/ondo/ikare.jpg", address:"Ikare Akoko" },
    { name: "Irele Market", img: "./markets/ondo/irele.jpg", address:"Irele" },
    { name: "Isikan Market", img: "./markets/ondo/isikan.jpeg", address:"Akure" },
    { name: "Oja Oba Market", img: "./markets/ondo/oja-oba.jpg", address:"Akure" },
    { name: "Oja Oshodi Market", img: "./markets/ondo/oja-oshodi.jpg", address:"Ondo Town" },
    { name: "Oja Owo Market", img: "./markets/ondo/oja-owo.jpg", address:"Owo" },
    { name: "Ore Market", img: "./markets/ondo/ore.jpg", address:"Ore, Odigbo" },
    { name: "Shasha Market", img: "./markets/ondo/shasha.jpg", address:"Akure" },
    { name: "Supare Market", img: "./markets/ondo/supare.jpg", address:"Supare Akoko" },
  ],

  Osun: [
    { name: "Alekuwodo Market", img: "./markets/osun/alekuwodo.jpg", address:"Osogbo" },
    { name: "Atakumosa Market", img: "./markets/osun/atakumosa.jpg", address:"Ilesa" },
    { name: "Erin Osun Market", img: "./markets/osun/erin-osun.jpg", address:"Erin-Osun" },
    { name: "Gbongan Market", img: "./markets/osun/gbongan.jpg", address:"Gbongan" },
    { name: "Ife Central Market", img: "./markets/osun/ife-central.jpg", address:"Ile-Ife" },
    { name: "Igbona Market", img: "./markets/osun/igbona.jpg", address:"Osogbo" },
    { name: "Ikirun Market", img: "./markets/osun/ikirun.jpg", address:"Ikirun" },
    { name: "Ila Orangun Market", img: "./markets/osun/ila-orangun.jpg", address:"Ila-Orangun" },
    { name: "Odo Ori Market", img: "./markets/osun/odo-ori.jpg", address:"Iwo" },
    { name: "Oja Ejigbo Market", img: "./markets/osun/ejigbo.jpeg", address:"Ejigbo" },
    { name: "Oja Oba Market", img: "./markets/osun/oja-oba.jpg", address:"Osogbo" },
    { name: "Oja Sekona Market", img: "./markets/osun/sekona.jpg", address:"Sekona" },
    { name: "Oja Timi Market", img: "./markets/osun/oja-timi.jpg", address:"Ede" },
    { name: "Okuku Market", img: "./markets/osun/okuku.jpg", address:"Okuku" },
    { name: "Owode Ede Market", img: "./markets/osun/owode-ede.jpg", address:"Ede" },
  ],

  Ekiti: [
    { name: "Aramoko Market", img: "./markets/ekiti/aramoko.jpg", address:"Aramoko-Ekiti" },
    { name: "Bisi Market", img: "./markets/ekiti/bisi.jpg", address:"Ado-Ekiti" },
    { name: "Erekesan Market", img: "./markets/ekiti/erekesan.jpg", address:"Ado-Ekiti" },
    { name: "Ifaki Market", img: "./markets/ekiti/ifaki.jpeg", address:"Ifaki-Ekiti" },
    { name: "Igede Market", img: "./markets/ekiti/igede.jpg", address:"Igede-Ekiti" },
    { name: "Ikere Ekiti Market", img: "./markets/ekiti/ikere.jpeg", address:"Ikere-Ekiti" },
    { name: "Iye Ekiti Market", img: "./markets/ekiti/iye.jpeg", address:"Iye-Ekiti" },
    { name: "Oja Oba Market", img: "./markets/ekiti/oja-oba.jpg", address:"Ado-Ekiti" },
    { name: "Oja Odo Oro Market", img: "./markets/ekiti/odo-oro.jpg", address:"Odo Oro-Ekiti" },
    { name: "Otun Ekiti Market", img: "./markets/ekiti/otun.jpeg", address:"Otun-Ekiti" },
  ],
};

module.exports = MARKETS; 
