const MARKETS = {
  Abia: [
    {
      name: "Ariaria International Market (Aba)",
      img: "./markets/BodijaMarket.jpg",
    },
    {
      name: "Umuahia Main Market (Umuahia)",
      img: "./markets/BodijaMarket.jpg",
    },
    { name: "Ubakala Market (Ubakala)", img: "./markets/BodijaMarket.jpg" },
    {
      name: "Aba International Market (Aba)",
      img: "./markets/BodijaMarket.jpg",
    },
    { name: "Ohia Market (Ohia)", img: "./markets/BodijaMarket.jpg" },
    { name: "Osisioma Market (Osisioma)", img: "./markets/BodijaMarket.jpg" },
    { name: "Omoba Market (Omoba)", img: "./markets/BodijaMarket.jpg" },
    {
      name: "Isiala Oboro Market (Isiala Oboro)",
      img: "./markets/BodijaMarket.jpg",
    },
    { name: "Umuike Market (Umuike)", img: "./markets/BodijaMarket.jpg" },
    { name: "Akwa Ibom Market (Aba)", img: "./markets/BodijaMarket.jpg" },
    { name: "Eziukwu Market (Aba)", img: "./markets/BodijaMarket.jpg" },
    { name: "Ogbuka Market (Umuahia)", img: "./markets/BodijaMarket.jpg" },
    { name: "Olokoro Market (Olokoro)", img: "./markets/BodijaMarket.jpg" },
    { name: "Ikwuano Market (Ikwuano)", img: "./markets/BodijaMarket.jpg" },
    { name: "Okeikpe Market (Okeikpe)", img: "./markets/BodijaMarket.jpg" },
    { name: "Uzuakoli Market (Uzuakoli)", img: "./markets/BodijaMarket.jpg" },
    { name: "Alaoji Market (Alaoji)", img: "./markets/BodijaMarket.jpg" },
    { name: "Obikabia Market (Obikabia)", img: "./markets/BodijaMarket.jpg" },
    { name: "Umuocham Market (Umuocham)", img: "./markets/BodijaMarket.jpg" },
    { name: "Nkwoegwu Market (Nkwoegwu)", img: "./markets/BodijaMarket.jpg" },
    { name: "Umuosu Market (Umuosu)", img: "./markets/BodijaMarket.jpg" },
    { name: "Oriendu Market (Oriendu)", img: "./markets/BodijaMarket.jpg" },
    { name: "Ndiegoro Market (Ndiegoro)", img: "./markets/BodijaMarket.jpg" },
  ],

  "Akwa-Ibom": [
    { name: "Abak Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Akwa Ibom Plaza", img: "./markets/BodijaMarket.jpg" },
    { name: "Eket Fish Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Eket Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ewet Housing Estate Market", img: "./markets/BodijaMarket.jpg" },
    {
      name: "Ikot Ekpene Fabric Market",
      img: "./markets/BodijaMarket.jpg",
    },
    {
      name: "Ikot Ekpene Main Market (Mbut Obio)",
      img: "./markets/BodijaMarket.jpg",
    },
    { name: "Itam Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Oron Fish Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Oron Main Market", img: "./markets/BodijaMarket.jpg" },
    {
      name: "Uyo Main Market (Uyo Central Market)",
      img: "./markets/BodijaMarket.jpg",
    },
    { name: "Urua Ekpa Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Urua Nsit Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Urua Akpan Ete Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Urua Abak Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ikot Ibritam Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ikot Abasi Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Urua Ikot Abasi Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Etim Ekpo Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ikono Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Urua Ikono Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Nto Edino Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Etinan Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Urua Etinan Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ikot Akpan Market", img: "./markets/BodijaMarket.jpg" },
  ],

  Anambra: [
    { name: "Afor Aguleri Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Afor Igwe Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Amaenyi Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Bridgehead Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Eke Amaobi Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Eke Awka Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Eke Ekwulobia Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Eke Market (Aguleri)", img: "./markets/BodijaMarket.jpg" },
    { name: "Electronics Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Nkwo Ekwulobia Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Nkwo Nnewi Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Nkwo Ogbe Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Nkwelle Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Nnewi Spare Parts Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ochanja Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Onitsha Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Relief Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Uru Market", img: "./markets/BodijaMarket.jpg" },
  ],
  Bauchi: [
    { name: "Alkaleri Central Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Badara Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Bagel Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Bakin Kura Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Bogoro Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Central Market Bauchi", img: "./markets/BodijaMarket.jpg" },
    { name: "Dagu Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Dass Central Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Darazo Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ganjuwa Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Goron Dutse Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Hawul Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Jama’a Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Kafin Baka Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Kafin Madaki Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Kafin Zaki Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Kari Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Kirfi Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Kiyawa Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Lere Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Lusa Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Magama Gumau Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Misau Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Muda Lawal Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ningi Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Railway Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Sabon Kaura Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Sade Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Soro Market", img: "./markets/BodijaMarket.jpg" },
    {
      name: "Tafawa Balewa Main Market",
      img: "./markets/BodijaMarket.jpg",
    },
    { name: "Tafawa Balewa Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Toro Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Warji Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Wanka Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Wunti Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Yelwa Market", img: "./markets/BodijaMarket.jpg",},
    { name: "Yuli Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Zindi Market", img: "./markets/BodijaMarket.jpg" },
  ],

  Bayelsa: [
    { name: "Akassa Fish Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Aleibiri Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Amabulou Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Amassoma Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Anyama-Ogbia Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Brass Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Darazo Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Egwema Local Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ekeremor Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ekeki Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Kolo Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Koluama Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Lobia Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Nembe-Bassey Market", img: "./markets/BodijaMarket.jpg" },

    { name: "Nembe Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ogboinbiri Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Odioma Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Odi-Gbene Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ogbia Town Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Oporoma Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Opolo Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ofoni Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Opu-Nembe Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Peretoru Local Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Sagbama Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Tombia Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Toru-Orua Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Twon Brass Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Yelwa Market", img: "./markets/BodijaMarket.jpg" },
  ],

  Benue: [
    { name: "Akaajime Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Enugu Road Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Gboko Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Gboko North Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Gboko South Market", img: "./markets/BodijaMarket.jpg" },
    { name: "GRA Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Katsina-Ala Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Makurdi Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Makurdi Modern Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Mbalagh Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Naka Road Market", img: "./markets/BodijaMarket.jpg" },
    { name: "North Bank Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ugbokolo Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Wurukum Market", img: "./markets/BodijaMarket.jpg" },
  ],

  Borno: [
    { name: "Baga Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Bama Central Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Bama Fish Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Bama Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Bama Sunday Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Biu Central Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Biu Friday Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Biu Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Biu Motor Park Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Customs Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Gamboru Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Kadamari Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Kwanan Gashu'a Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Kwaya Kusar Market", img: "./markets/BodijaMarket.jpg" },
    {
      name: "Maiduguri Main Market (Bama Road Market)",
      img: "./markets/BodijaMarket.jpg",
    },
    { name: "Ngamdu Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Old Maiduguri Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Wulgo Market", img: "./markets/BodijaMarket.jpg" },
  ],

  CrossRiver: [
    { name: "Akamkpa Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Akamkpa Timber Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Akpabuyo Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Bendeghe Ekiem Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Bekwarra Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Biase Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Biase Town Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Boki Agricultural Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Boki Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Danare Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ediba Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Etomi Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Igede Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Igede Weekly Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ikom Cattle Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ikom Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Iso-bendghe Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Itigidi Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Marian Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Obanliku Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Obudu Cattle Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Obudu Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Obubra Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Obubra Town Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Odukpani Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Odukpani Timber Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ogoja Cattle Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ogoja Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ofutop Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ugep Cattle Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ugep Main Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ukpe Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ukelle Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Worji Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Yala Market", img: "./markets/BodijaMarket.jpg" },
  ],

  Lagos: [
    { name: "Agbalata Market Badagry", img: "./markets/BodijaMarket.jpg" },
    {
      name: "Alaba International Market",
      img: "./markets/BodijaMarket.jpg",
    },
    { name: "Ajah Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Aratumi Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Balogun Market, Lagos Island", img: "./markets/BodijaMarket.jpg" },
    { name: "Bar Beach Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Computer Village", img: "./markets/BodijaMarket.jpg",address:"Computer Village, Lagos Island" },
    {
      name: "Èbúté Èrò Market, Lagos Island",
      img: "./markets/BodijaMarket.jpg",
    },
    { name: "Epe Fish Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Iyana-Iba Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ikotun Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Idumota Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ita Faji Market", img: "./markets/BodijaMarket.jpg" },
    {
      name: "Isale Eko Market, Lagos Island",
      img: "./markets/BodijaMarket.jpg",
    },
    {
      name: "Jankarra Market, Lagos Island",
      img: "./markets/BodijaMarket.jpg",
    },
    { name: "Ladipo Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Lekki Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Agboju Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Daleko Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Morocco I and II markets", img: "./markets/BodijaMarket.jpg" },
    { name: "Mushin Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Oyingbo Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Mile 12 Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Oniru New Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Fespar Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Oshodi Market", img: "./markets/BodijaMarket.jpg" },
    {
      name: "Rauf Aregbesola Market",
      img: "./markets/BodijaMarket.jpg",
    },
    { name: "Téjúoshó Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Sangotedo Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ajuwe Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Jakande Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Akodo Market, Epe", img: "./markets/BodijaMarket.jpg" },
    {
      name: "Boundary Seafood Market",
      img: "./markets/BodijaMarket.jpg",
    },
    { name: "Apongbo Market", img: "./markets/BodijaMarket.jpg" },
    {
      name: "Liverpool Crayfish Market",
      img: "./markets/BodijaMarket.jpg",
    },
    { name: "Arena Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Cele Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Ijesha Market, Ijeshatedo", img: "./markets/BodijaMarket.jpg" },
    { name: "State Market", img: "./markets/BodijaMarket.jpg" },
    { name: "Agege Market", img: "./markets/BodijaMarket.jpg" },
  ],
};

module.exports = MARKETS;
